// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy4fTD_nXKIZZxTH6hAxXWueyPigxty9U',
    appId: '1:594801867619:android:8fcc8ef7ec5fb0ad373156',
    messagingSenderId: '594801867619',
    projectId: 'aura-app-16fc3',
    storageBucket: 'aura-app-16fc3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCovogXQ885Wq3oZjmO4J6nwXelPkOj934',
    appId: '1:594801867619:ios:11845337822ebd9a373156',
    messagingSenderId: '594801867619',
    projectId: 'aura-app-16fc3',
    storageBucket: 'aura-app-16fc3.firebasestorage.app',
    androidClientId: '594801867619-ibqgng65ulbgc4e0fi9p9bp8lheqqmlm.apps.googleusercontent.com',
    iosClientId: '594801867619-hkp5skuga9q2eg4cnest0pk98jbo7voh.apps.googleusercontent.com',
    iosBundleId: 'com.aprd.auraApp',
  );

}